name: selfstudy_oai
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - notebook>=6.4.0
  - pytest>=6.2.0
  - black>=21.5b2
  - isort>=5.9.0
  - flake8>=3.9.0
  - pip
  - pip:
    - -r requirements.txt 