name: Notebook Checks

on:
  push:
    branches: [ main ]
    paths:
      - '**.ipynb'
  pull_request:
    branches: [ main ]
    paths:
      - '**.ipynb'

jobs:
  notebook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nbformat nbconvert
    - name: Check notebook format
      run: |
        find . -name "*.ipynb" -exec jupyter nbconvert --clear-output --inplace {} \;
        find . -name "*.ipynb" -exec python -c "import nbformat; nbformat.read('{}', nbformat.NO_CONVERT)" \; 